[package]
name = "id-map"
description = "Data structure of values indexed by IDs."
license = "MIT"
version = "0.1.0"
authors = ["Andrew Hickman <andrew.hickman1@sky.com>"]

[dependencies]
bit-set = "0.4.0"
bit-vec = "0.4.0"